FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="React Webpack for FrontEnd of the Library API"

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm","run","start"]
