version: "3.9"

services:
  library-api:
    image: server_mern
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server-mern
    volumes:
      - /app/node_modules
      - ./server:/app
    # ports:
    #   - 5000:5000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - library-mern-api
  mongodb:
    image: mongo
    container_name: mongo-mern
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - library-mern-api
  mongo-express:
    image: mongo-express
    container_name: mongo-express-mern
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes:
      - mongodb-data
    networks:
      - library-mern-api
  client:
    image: client_mern
    container_name: frontend-mern
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/node_modules
      - ./client:/app
    # ports:
    #   - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - library-api
    networks:
      - library-mern-api
  nginx:
    image: nginx_mern
    container_name: nginx-mern
    restart: always
    depends_on:
      - library-api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    networks:
      - library-mern-api
networks:
  library-mern-api:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
